Feat/redisgn mobile app
NhiSty/Colibris pull request #40
Opened 2024-07-12 17:22 UTC by sDev67

- changing de design de l'app mobile
- fixing de nombreux bug
- merging de la branche fix/route qui utilise désormais un go routeur dans le front et bo

2024-07-12 23:24 UTC, ThomasDev6 commented
J'ai rencontré plusieurs problème durant la QA : 

- On se retrouve coincé quand on va sur la conv d'une coloc et que l'on clique plrs fois sur la fleche pour revenir en arrière en switch entre la liste de tâche et la conversation.

https://github.com/user-attachments/assets/e11769a9-584e-45bd-aaa3-89169914788d

- Au lancement de l'app, il n'y a pas la bottomBar, elle apparait quand on va sur un colocation et que l'on clique sur home dans la bottombar.
- 
<img width="388" alt="Capture d’écran 2024-07-13 à 01 11 10" src="https://github.com/user-attachments/assets/30278e0d-8370-4a17-bf02-3c9b85e829b8">

2024-07-12 23:28 UTC, ThomasDev6 requested changes

2024-07-12 23:28 UTC, ThomasDev6 commented on .DS_Store
Normal qu'il y ait ce fichier ici ?

2024-07-13 09:48 UTC, sDev67 commented on .DS_Store
- le ds store non c'est une erreur de ma part
- On se retrouve coincé quand on va sur la conv d'une coloc et que l'on clique plrs fois sur la fleche pour revenir en arrière en switch entre la liste de tâche et la conversation.
--> c'est un comportement normal, c'est voulu, tu vois les listes de tache, tu cliques sur chat, tu as en mémoire la route d'avant, donc quand tu fais retour tu vois la listes des taches et ici, tu as en memoire le chat donc quand tu refais retour depuis liste des taches tu reviens dans chat
- et pour la bottomNavBar c'est un oublie de ma part je corrige

2024-07-13 11:20 UTC, ThomasDev6 approved these changes

2024-07-13 11:22 UTC, merged